### ISSUE TITLE
Plugin fails to build for Ghidra 9.2

### ISSUE THREAD

**Issue by fmagin** [VDOO-Connected-Trust/KotlinScriptProvider#2]
Plugin fails to build with Ghidra 9.2 due to the issues discussed in https://github.com/NationalSecurityAgency/ghidra/issues/2490
 
```
> Task :compileJava
/home/fmagin/gits/KotlinScriptProvider/src/main/java/KotlinScriptProvider/KotlinScriptProvider.java:34: error: cannot find symbol
    private JavaScriptClassLoader loader = new JavaScriptClassLoader();
            ^
  symbol:   class JavaScriptClassLoader
  location: class KotlinScriptProvider
/home/fmagin/gits/KotlinScriptProvider/src/main/java/KotlinScriptProvider/KotlinScriptProvider.java:34: error: cannot find symbol
    private JavaScriptClassLoader loader = new JavaScriptClassLoader();
                                               ^
  symbol:   class JavaScriptClassLoader
  location: class KotlinScriptProvider
/home/fmagin/gits/KotlinScriptProvider/src/main/java/KotlinScriptProvider/KotlinScriptProvider.java:97: error: cannot find symbol
        loader = new JavaScriptClassLoader(); // this forces the script class to be reloaded
                     ^
  symbol:   class JavaScriptClassLoader
  location: class KotlinScriptProvider
/home/fmagin/gits/KotlinScriptProvider/src/main/java/KotlinScriptProvider/KotlinScriptProvider.java:111: error: cannot find symbol
                GhidraScriptUtil.getClassFileByResourceFile(sourceFile, className);
                                ^
  symbol:   method getClassFileByResourceFile(ResourceFile,String)
  location: class GhidraScriptUtil
/home/fmagin/gits/KotlinScriptProvider/src/main/java/KotlinScriptProvider/KotlinScriptProvider.java:183: error: cannot find symbol
        ScriptInfo info = GhidraScriptUtil.getScriptInfo(sourceFile);
                                          ^
  symbol:   method getScriptInfo(ResourceFile)
  location: class GhidraScriptUtil
/home/fmagin/gits/KotlinScriptProvider/src/main/java/KotlinScriptProvider/KotlinScriptProvider.java:230: error: cannot find symbol
                GhidraScriptUtil.getScriptCompileOutputDirectory(sourceFile).getAbsolutePath();
                                ^
  symbol:   method getScriptCompileOutputDirectory(ResourceFile)
  location: class GhidraScriptUtil
/home/fmagin/gits/KotlinScriptProvider/src/main/java/KotlinScriptProvider/KotlinScriptProvider.java:321: error: cannot find symbol
            return Class.forName(clazzName, true, new JavaScriptClassLoader());
                                                      ^
  symbol:   class JavaScriptClassLoader
  location: class KotlinScriptProvider
/home/fmagin/gits/KotlinScriptProvider/src/main/java/KotlinScriptProvider/KotlinScriptProvider.java:405: error: cannot find symbol
        List<ResourceFile> dirs = GhidraScriptUtil.getScriptBinDirectories();
                                                  ^
  symbol:   method getScriptBinDirectories()
  location: class GhidraScriptUtil
Note: /home/fmagin/gits/KotlinScriptProvider/src/main/java/KotlinScriptProvider/KotlinScriptProvider.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
8 errors

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5s
1 actionable task: 1 executed
```
